Repository libseccomp-rs/libseccomp-rs, pull requests merged in 2021-12, with the labels that each got.

#26 Add `get_no_new_privs_bit` function
  libseccomp/src/lib.rs
Labels: enhancement

#32 export_{pfc,bpf} take a &mut T where T: AsRawFd
  libseccomp/src/lib.rs
Labels: enhancement

#31 Rustify get_native_arch
  libseccomp/src/lib.rs
Labels: enhancement

#44 Add scmp_cmp! macro
  libseccomp/src/lib.rs
Labels: enhancement

#49 Add static link check for musl-libc to CI
  .github/actions/setup/action.yaml
  .github/workflows/build-test.yaml
  scripts/install_libseccomp.sh
Labels: enhancement

#51 Use dup3 instead of dup2
  README.md
  libseccomp/src/lib.rs
Labels: documentation, test

#52 Improve `SeccompError`
  libseccomp/src/error.rs
Labels: enhancement, test

#59 Return Err when the return value of the libseccomp library is not zero
  libseccomp/src/lib.rs
Labels: bug

#58 Add unit tests for `export_bpf` and `export_pfc`
  libseccomp/src/lib.rs
Labels: do-not-merge

#61 Add tests for deprecated functions
  libseccomp/src/lib.rs
Labels: test

#47 Internal refactoring for the add_rule rework
  libseccomp/src/lib.rs
Labels: enhancement, do-not-merge

#67 Update README.md and Cargo.toml
  README.md
  libseccomp-sys/Cargo.toml
  libseccomp-sys/README.md
  libseccomp/Cargo.toml
  libseccomp/README.md
Labels: documentation

#71 Add documentation check to CI
  .github/workflows/build-test.yaml
Labels: ci

#70 Make the format of doc comments consistent
  README.md
  libseccomp/src/error.rs
  libseccomp/src/lib.rs
Labels: documentation, do-not-merge

#73 Update CHANGELOG
  CHANGELOG.md
Labels: documentation
