Repository libseccomp-rs/libseccomp-rs, pull requests merged in 2022-03, with the labels that each got.

#119 Lift tests that only test public API into tests/ dir
  libseccomp/src/lib.rs
  libseccomp/src/notify.rs
  libseccomp/tests/global_reset.rs
  libseccomp/tests/notify.rs
  libseccomp/tests/tests.rs
Labels: test

#122 example: Fix is_arch_present for aarch64
  libseccomp/src/lib.rs
Labels: documentation

#123 impl From<ScmpSyscall> for i32
  CHANGELOG.md
  libseccomp/src/lib.rs
  libseccomp/tests/tests.rs
Labels: enhancement

#126 impl fmt::Display for ScmpSyscall
  CHANGELOG.md
  libseccomp/src/lib.rs
  libseccomp/tests/tests.rs
Labels: enhancement

#127 impl PartialEq i32 and ScmpSyscall
  CHANGELOG.md
  libseccomp/src/lib.rs
  libseccomp/tests/tests.rs
Labels: enhancement

#129 Move types into own modules
  libseccomp/src/action.rs
  libseccomp/src/arch.rs
  libseccomp/src/arg_compare.rs
  libseccomp/src/compare_op.rs
  libseccomp/src/filter_attr.rs
  libseccomp/src/lib.rs
  libseccomp/src/version.rs
Labels: enhancement

#131 Re-export notify module
  CHANGELOG.md
  libseccomp/src/lib.rs
  libseccomp/tests/notify.rs
Labels: enhancement
