Repository libseccomp-rs/libseccomp-rs, pull requests merged in 2022-01, with the labels that each got.

#80 Add some more examples to function documentation
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: documentation

#84 Specify libc version by SemVer
  libseccomp/Cargo.toml
Labels: invalid

#89 Add doc comment format to README.md's contributing section
  README.md
Labels: documentation

#87 Add {get,set}_badarch_action function
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#91 Add `reset_global_state()`
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#93 Make more types usable with HashMap
  CHANGELOG.md
  libseccomp/src/error.rs
  libseccomp/src/lib.rs
  libseccomp/src/notify.rs
Labels: enhancement

#82 Add ScmpSyscall + syscall_resolve_name_rewrite
  CHANGELOG.md
  libseccomp/src/lib.rs
  libseccomp/src/notify.rs
Labels: enhancement

#97 api: Add get_default_action()
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#99 api: Rename {get,set}_badarch_action to {get,set}_act_badarch
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#100 api: Rename get_default_action to get_act_default
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#98 Add #[must_use] to some function in libseccomp
  libseccomp-sys/src/lib.rs
  libseccomp/src/lib.rs
  libseccomp/src/notify.rs
Labels: enhancement

#101 Update example in README.md to use ScmpSyscall
  README.md
Labels: documentation

#102 Rename {get,set}_no_new_privs_bit to {get,set}_ctl_nnp
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#104 Add ScmpFilterContext::{get,set}_ctl_ssb
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#105 Add ScmpFilterContext::{get,set}_ctl_optimize
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#106 Add ScmpFilterContext::{get,set}_api_sysrawrc
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement

#108 Add ScmpFilterContext::{get,set}_ctl_tsync
  CHANGELOG.md
  libseccomp/src/lib.rs
Labels: enhancement
