Repository libseccomp-rs/libseccomp-rs, pull requests merged in 2023-07, with the labels that each got.

#225 ci: Add test for the upstream libseccomp library
  .github/workflows/build-test.yaml
  scripts/install_libseccomp.sh
Labels: ci

#229 ci: msrv and coverage jobs use the main branch of the libseccomp
  .github/workflows/build-test.yaml
Labels: bug, ci

#228 Drop the libseccomp < 2.5.0 support
  .github/workflows/build-test.yaml
  CHANGELOG.md
  README.md
  libseccomp/build.rs
  libseccomp/src/filter_context.rs
  libseccomp/src/lib.rs
  libseccomp/src/version.rs
  libseccomp/tests/notify.rs
  libseccomp/tests/tests.rs
Labels: enhancement

#219 Builder
  CHANGELOG.md
  libseccomp/src/filter_context.rs
  libseccomp/src/lib.rs
  libseccomp/tests/tests.rs
Labels: enhancement

#227 error: Add SeccompError::sysrawrc() api
  CHANGELOG.md
  libseccomp/src/error.rs
Labels: enhancement

#230 test: Improve test coverage
  libseccomp/src/error.rs
  libseccomp/tests/tests.rs
Labels: test

#217 `seccomp_export_bpf_mem`
  CHANGELOG.md
  libseccomp/src/filter_context.rs
  libseccomp/tests/tests.rs
Labels: enhancement
